name: Deploy with Puppeteer

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
    tags:
      - "*"
  release:
    types:
      - published
    branches:
      - development

jobs:
  run-puppeteer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Process index.html
        run: node filo.js index.html

      - name: Run Puppeteer script
        env:
            APP_LOCATION: ${{ secrets.APP_LOCATION }}
            APP_LOCATION_DEVELOPMENT: ${{ secrets.APP_LOCATION_DEVELOPMENT }}
        run: node puppeteer-deploy.js